export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SALES = 'SALES',
  TAILOR = 'TAILOR',
  CUTTER = 'CUTTER',
  PRODUCTION_MANAGER = 'PRODUCTION_MANAGER',
  QC = 'QC',
  STORE_MANAGER = 'STORE_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT'
}

export enum CustomerType {
  INDIVIDUAL = 'INDIVIDUAL',
  TAILOR_CUSTOMER = 'TAILOR_CUSTOMER',
  BOUTIQUE = 'BOUTIQUE',
  BRAND = 'BRAND',
  WHOLESALE = 'WHOLESALE'
}

export enum GenderCategory {
  MEN = 'MEN',
  WOMEN = 'WOMEN',
  KIDS = 'KIDS',
  UNISEX = 'UNISEX'
}

export enum OrderType {
  BESPOKE_TAILORING = 'BESPOKE_TAILORING',
  BULK_MANUFACTURING = 'BULK_MANUFACTURING',
  ALTERATION = 'ALTERATION',
  SAMPLE = 'SAMPLE'
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  IN_CUTTING = 'IN_CUTTING',
  IN_STITCHING = 'IN_STITCHING',
  FINISHING = 'FINISHING',
  TRIAL_READY = 'TRIAL_READY',
  QC_IN_PROGRESS = 'QC_IN_PROGRESS',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}

export enum ProductionStage {
  CUTTING = 'CUTTING',
  STITCHING = 'STITCHING',
  FINISHING = 'FINISHING',
  QC_INSPECTION = 'QC_INSPECTION',
  IRONING_PACKING = 'IRONING_PACKING',
  COMPLETED = 'COMPLETED'
}

export enum QCStatus {
  PENDING = 'PENDING',
  PASSED = 'PASSED',
  REWORK_REQUIRED = 'REWORK_REQUIRED',
  REJECTED = 'REJECTED'
}

export enum DefectType {
  STITCHING_DEFECT = 'STITCHING_DEFECT',
  MEASUREMENT_MISMATCH = 'MEASUREMENT_MISMATCH',
  FABRIC_DAMAGE = 'FABRIC_DAMAGE',
  COLOR_MISMATCH = 'COLOR_MISMATCH',
  STAIN = 'STAIN',
  TRIM_DEFECT = 'TRIM_DEFECT',
  OTHER = 'OTHER'
}

export enum InventoryCategory {
  FABRIC = 'FABRIC',
  BUTTON = 'BUTTON',
  ZIPPER = 'ZIPPER',
  THREAD = 'THREAD',
  LINING = 'LINING',
  LABEL = 'LABEL',
  PACKING_MATERIAL = 'PACKING_MATERIAL',
  ACCESSORY = 'ACCESSORY',
  OTHER = 'OTHER'
}

export enum StockMovementType {
  PURCHASE_IN = 'PURCHASE_IN',
  PRODUCTION_CONSUMPTION = 'PRODUCTION_CONSUMPTION',
  DAMAGE_WASTAGE = 'DAMAGE_WASTAGE',
  RETURN = 'RETURN',
  ADJUSTMENT = 'ADJUSTMENT'
}

export enum PaymentMethod {
  CASH = 'CASH',
  UPI = 'UPI',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  RAZORPAY = 'RAZORPAY',
  OTHER = 'OTHER'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED'
}

export enum WageType {
  PIECE_RATE = 'PIECE_RATE',
  MONTHLY_SALARY = 'MONTHLY_SALARY',
  DAILY_WAGE = 'DAILY_WAGE'
}

export enum PriorityLevel {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}
